Magisterka/Controllers/BazaController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Magisterka.Models;
using System.Reflection;

namespace Magisterka.Controllers
{
    public class BazaController : Controller
    {
        private readonly MagisterkaContext _context;

        public class ButtonModel
        {
            public string content { get; set; }
            public bool isPrimary { get; set; }

        }
        public BazaController(MagisterkaContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            Baza model = new Baza();
            List<ZmiennaItem> zmienne = model.Zmienne;
            return View(await _context.Baza.ToListAsync());
        }

        // GET: Baza/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            Baza model = new Baza();
            List<ZmiennaItem> zmienne = model.Zmienne;
            if (id == null)
            {
                return NotFound();
            }

            var baza = await _context.Baza
                .FirstOrDefaultAsync(m => m.Id == id);
            if (baza == null)
            {
                return NotFound();
            }
            return View(baza);
        }

        // GET: Baza/Create
        public IActionResult Create()
        {
            Baza model = new Baza();
            List<ZmiennaItem> zmienne = model.Zmienne;

            int x;
            string cos;
            x = zmienne.Count();
            for (int n = 0; n < x; ++n)
            {
                cos = zmienne[n].Zmienna;
                if (TempData[zmienne[n].Zmienna] != null)
                {
                    string a = TempData[cos].ToString();
                    model.GetType().GetProperty(cos).SetValue(model, a, null);
                    TempData.Remove(cos);
                }

            }

            return View(model);
        }
        // POST: Baza/Create
 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DATA,Nazwa,Opis,RQg,RFi,RQ0,RDz,Rtinf,Rt,RL,KQc,KCOP,KQ0,KH,KZ,KB,KTgr,DT,KTgm,Ktp,Kalfag,Kalfap,KAgr,Agr,KAr,Kdw,Kdz,KK,KC,KqL,Kqh,Kep,KLp,SQv,SLo,SLw,SdLw,SQc,SCOP,STsp,SQ0,BDz,BDw,Blambdar,Bn,Bgamma,BQ,BCOP,BTgr,BTgo,BRr,BRgr,Btp,Btg,BL")] Baza baza)
        {
 
            if (ModelState.IsValid)
                {
                    _context.Add(baza);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }      
            return View(baza);
        }

        // GET: Baza/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            Baza model = new Baza();
            List<ZmiennaItem> zmienne = model.Zmienne;
            if (id == null)
            {
                return NotFound();
            }

            var baza = await _context.Baza.FindAsync(id);
            if (baza == null)
            {
                return NotFound();
            }
            return View(baza);
        }

        // POST: Baza/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DATA,Nazwa,Opis,RQg,RFi,RQ0,RDz,Rtinf,Rt,RL,KQc,KCOP,KQ0,KH,KZ,KB,KTgr,DT,KTgm,Ktp,Kalfag,Kalfap,KAgr,Agr,KAr,Kdw,Kdz,KK,KC,KqL,Kqh,Kep,KLp,SQv,SLo,SLw,SdLw,SQc,SCOP,STsp,SQ0,BDz,BDw,Blambdar,Bn,Bgamma,BQ,BCOP,BTgr,BTgo,BRr,BRgr,Btp,Btg,BL")] Baza baza)
        {
            if (id != baza.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(baza);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BazaExists(baza.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(baza);
        }

        // GET: Baza/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            Baza model = new Baza();
            List<ZmiennaItem> zmienne = model.Zmienne;
            if (id == null)
            {
                return NotFound();
            }

            var baza = await _context.Baza
                .FirstOrDefaultAsync(m => m.Id == id);
            if (baza == null)
            {
                return NotFound();
            }
            return View(baza);
        }

        // POST: Baza/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var baza = await _context.Baza.FindAsync(id);
            _context.Baza.Remove(baza);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BazaExists(int id)
        {
            return _context.Baza.Any(e => e.Id == id);
        }
    }
}

Magisterka/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pl-PL">
<head>
    <meta charset="utf-16" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Magisterka</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Główna</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Kolektor Poziomy<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a asp-area="" asp-controller="Home" asp-action="PoziomyRubik">Skrócone obliczenia wg. Rubika</a></li>
                            <li class="divider"></li>
                            <li><a asp-area="" asp-controller="Home" asp-action="PoziomyKopec">Szczegółowe obliczenia wg. Kopcia </a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sonda Pionowa<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a asp-area="" asp-controller="Home" asp-action="Pionowy">Skrócone obliczenia sondy pionowej</a></li>
                            <li class="divider"></li>
                            <li><a asp-area="" asp-controller="Home" asp-action="BoseParker">Algorytm Bose-Parkera</a></li>
                        </ul>
                    </li>
                    <li><a asp-area="" asp-controller="Baza" asp-action="Index">Podgląd Bazy</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">O mnie</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - Praca Magisterska</p>
        </footer>
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>